In [2]:
import numpy as np


# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [6]:
np_array = np.array([i for i in range(0, 9)])
np_array
np_array.ndim

1

Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [21]:
rs_np_array = np_array.reshape(3, 3)
rs_np_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Access the element at the second row, second column.


In [25]:
rs_np_array[1,1]

4

Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [27]:
#addition:
rs_np_array[1,2]+ rs_np_array[2,1] # 5 + 7 = 12

12

In [29]:
#multiplication
rs_np_array[1] * rs_np_array[2] # row 2 multiplied by row 3 

array([18, 28, 40])

In [33]:
#subtraction
arr_1 = np.array([2, 2, 4])
arr_2 = np.array([1, 3, 4])

sub_arr = np.subtract(arr_1, arr_2)
sub_arr


array([ 1, -1,  0])

In [44]:
#division
div_arr = np.divide(arr_1, arr_2)
div_arr

array([2.        , 0.66666667, 1.        ])

Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [17]:
np_arr = np.array([1,2,3,4,5])
np.sum(np_arr)

15

In [18]:
np.mean(np_arr)

3.0

In [19]:
np.std(np_arr)

1.4142135623730951

Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [23]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshape_arr = arr.reshape(2, 3)
reshape_arr

array([[1, 2, 3],
       [4, 5, 6]])


# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [7]:
random_array = np.random.randint(0,100, size=(5,5))
random_array

array([[38, 18, 85,  4, 54],
       [56, 32, 33, 69, 61],
       [93, 68, 84,  6, 48],
       [96, 50,  6, 36, 95],
       [ 9, 72, 54, 60, 33]])

Replace all values in the sub-array with a specific value.


In [9]:
start_row, end_row = 1, 3
start_col, end_col = 1, 3
specific_value = 0

random_array[start_row:end_row+1, start_col:end_col+1] = specific_value

random_array

array([[38, 18, 85,  4, 54],
       [56,  0,  0,  0, 61],
       [93,  0,  0,  0, 48],
       [96,  0,  0,  0, 95],
       [ 9, 72, 54, 60, 33]])

Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].


In [12]:
array = np.array([[1,2], [3,4], [5,6],[7,8]])

sub_array = array[1:3]
sub_array

array([[3, 4],
       [5, 6]])


# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [38]:
arr_2d = np.array([[0, 1, 2],[0, 1, 2],[0, 1, 2]])
arr_2d

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [47]:
arr_1d = np.arange(3).reshape(3)
added_array = arr_1d + arr_2d
print(f'Original Array of 1D:\n{arr_1d}')
print()
print(f'Original Array of 2D:\n{arr_2d}')
print()
print(f'Result of summed array:\n{added_array}')

Original Array of 1D:
[0 1 2]

Original Array of 2D:
[[0 1 2]
 [0 1 2]
 [0 1 2]]

Result of summed array:
[[0 2 4]
 [0 2 4]
 [0 2 4]]


# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.


In [88]:
array_1 = np.random.randint(0, 9, size =(3,3))
array_2 = np.random.randint(0,9, size =(3,3))

In [89]:
horizontal_concatenation = np.concatenate((array_1, array_2), axis = 0)
horizontal_concatenation

array([[7, 7, 7],
       [3, 7, 1],
       [8, 5, 4],
       [7, 8, 0],
       [3, 4, 4],
       [0, 5, 7]])

In [90]:
vertical_concatenation = np.concatenate((array_1, array_2), axis = 1)
vertical_concatenation

array([[7, 7, 7, 7, 8, 0],
       [3, 7, 1, 3, 4, 4],
       [8, 5, 4, 0, 5, 7]])

# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

In [3]:
array =  np.array([1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5])
count_dict = {}

for i in array:
    if i in count_dict:
        count_dict[i] += 1
    else:
        count_dict[i] = 1
mode = None
max_count = 0

for key, value in count_dict.items():
    if value> max_count:
        max_count = value
        mode = key

print(mode)


1


# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

